import React from 'react'

export const metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <div>Home page</div>
  )
}
